Use a reference of problem for set_problem()
martinjrobins/diffsol pull request #4
Opened 2024-03-21 13:44 UTC by mhovd

During simulation it may be necessary to update the state, which also requires the problem. Previously `set_problem()` consumed `problem`, but this change instead calls for a reference. The problem itself is small, and as such the clone should not be especially expensive.

2024-03-21 13:44 UTC, mhovd commented
Alternatively a different solution focused on updating the state without requiring a new call to `set_problem()`? It feels like an XY problem.

2024-03-21 13:56 UTC, martinjrobins requested changes
thanks @mhovd, few minor changes below to reduce some lines of unnessessary code:

2024-03-21 13:56 UTC, martinjrobins commented on src/ode_solver/bdf.rs
> +        let problem_clone = problem.clone();
could collapse these three lines into one?:
```rust
let problem_clone = problem.clone();
self.ode_problem = Some(problem_clone);
let problem = self.ode_problem.as_ref().unwrap();
```
```rust
self.ode_problem = Some(problem.clone());
// can just use the input problem reference after this as `problem`
```

2024-03-21 13:56 UTC, martinjrobins commented on src/ode_solver/mod.rs
>          let problem = problem.clone();
```suggestion
```

2024-03-21 13:56 UTC, martinjrobins commented on src/ode_solver/mod.rs
>          let problem = problem.clone();
```suggestion
```

2024-03-21 14:42 UTC, martinjrobins commented
> Alternatively a different solution focused on updating the state without requiring a new call to `set_problem()`? It feels like an XY problem.

As I see it, the old solver method needs to know if the state has been altered, so it can reset its own internal state. You could either:
- have the ode solver method own the state, so to alter the state you need to call a method on the ode solver method
- have a `reset()` function on the ode solver method so it knows to reset its internal state (but keep the current problem). This will be pretty similar to the current `set_problem` solution, just with one less arg

2024-03-22 11:17 UTC, Siel commented
I understand that sometimes it is necessary to update the state (and if we're planning to support events this will be happening all the time). But I'm not sure about the approach.

Wouldn't it be better if we have a sort of orchestrator that sub divides the time vector to stop the solver at the event's time, and then modifies the state by changing the initial condition of the next simulation?

I know there is some overhead to this approach, namely the need to interpolate for every event time, but this approach (I think) can be more easily extrapolated when new solvers are implemented.

2024-03-22 12:02 UTC, martinjrobins commented
> 
> Wouldn't it be better if we have a sort of higher level orchestrator that sub divides the time vector to stop the solver at the event's time, and then modifies the state by changing the initial condition of the next simulation?

Agreed, I think this PR is to sort out the api on the solver methods that this orchestrator could use to implement this.

2024-03-23 21:49 UTC, martinjrobins approved these changes
looks great, thanks @mhovd

2024-03-23 21:49 UTC, merged